let radio = document.querySelectorAll('input[type="radio"]');
let firstName = document.getElementById("firstName");
let lastName = document.getElementById("lastName");
let emailId = document.getElementById("emailId");
let phoneNumber = document.getElementById("phoneNumber");
let zipcode = document.getElementById("zipcode");
let checkbox = document.querySelectorAll('input[type="checkbox"]');
let feedbackForm = document.getElementById("feedbackForm");
let comments = document.getElementById("comments");
